/**
 * This file is automatically generated via scripts.
 *
 * Do not manually edit it!
 */

export const allExamplePaths: ReadonlyArray<string> = [
    '/content/bitgen-0-0.html',
    '/content/bitgen-0-1.html',
    '/content/bitgen-0-2.html',
    '/content/bitgen-0-3.html',
    '/content/bitgen-0-4.html',
    '/content/bitgen-0-5.html',
    '/content/bitgen-1-0.html',
    '/content/bitgen-1-1.html',
    '/content/bitgen-1-2.html',
    '/content/bitgen-1-3.html',
    '/content/bitgen-1-4.html',
    '/content/bitgen-1-5.html',
];
