export type GeneratedFile = {filePath: string; fileContents: string};

export const generatedFileTsComment = `/**
 * This file is automatically generated via scripts.
 *
 * Do not manually edit it!
 */
`;
